### ISSUE TITLE
Setting spawn-on-join to FALSE doesn't work

### ISSUE THREAD

**Issue by shineXdark** [Bluecoaster455/WorldSpawn#3]
I checked EssentialsX and Multiverse configs to make sure I'm correct.
It seems like whenever I join back to the world it teleports me to the Spawn I set on WorldSpawn.

Here's the config in case you wanted to check it yourselves :

Context : Survival worlds are world, world_nether, and world_the_end (worlds). Creative are creativelobby, and creative (worlds). the hub is the lobby (world).
```
# 
#         If you are experiencing console errors, shut down the server and rename the "world"
#         setting of hub and spawns sections to your main world name!

language: EN
hub-enabled: true
hub-on-join: true
spawn-on-join: false
spawn-on-respawn: true
spawn-delay: 3
hub-delay: 3
hub:
  world: lobby
  x: 566.330568671262
  y: 29.0
  z: 85.35599335070908
  yaw: 315.15005
  pitch: 6.000013
spawns:
  world:
    world: world
    x: -118.04191251414125
    y: 70.0
    z: -61.49643093794891
    yaw: -269.39963
    pitch: 0.14997923
    spawn-on-respawn: true
  creativelobby:
    world: creativelobby
    x: -23.34043033504902
    y: 14.0
    z: -264.4416360955435
    yaw: -90.74991
    pitch: 3.150002
  lobby:
    world: lobby
    x: 566.330568671262
    y: 29.0
    z: 85.35599335070908
    yaw: 309.00052
    pitch: 17.849974
    spawn-on-respawn: true
  world_the_end:
    spawn-on-respawn: true
    world: world
    x: -118.04191251414125
    y: 70.0
    z: -61.49643093794891
    yaw: -269.39963
    pitch: 0.14997923
  world_nether:
    spawn-on-respawn: true
    world: world
    x: -118.04191251414125
    y: 70.0
    z: -61.49643093794891
    yaw: -269.39963
    pitch: 0.14997923

```
